In [38]:
import torch
from torchvision import transforms
from torch.utils.data import DataLoader
from torchvision.datasets import ImageFolder
import torchvision.transforms as tt
from PIL import Image
import numpy as np
import typing
import os
import os.path as path
import pandas as pd
from tqdm.notebook import tqdm

In [2]:
class BinaryAccuracy:
    def __init__(
            self,
            logits: bool = True,
            reduction: typing.Callable[
                [
                    torch.Tensor,
                ],
                torch.Tensor,
            ] = torch.mean,
    ):
        self.logits = logits
        if logits:
            self.threshold = 0
        else:
            self.threshold = 0.5

        self.reduction = reduction

    def __call__(self, y_pred, y_true):
        return self.reduction(((y_pred > self.threshold) == y_true.bool()).float())


In [56]:
stats = (0.5, 0.5, 0.5), (0.5, 0.5, 0.5)
tt_transform = tt.Compose([tt.Resize(128),
                             tt.CenterCrop(128),
                             tt.ToTensor(),
                             tt.Normalize(*stats)])
defect_ds = ImageFolder("data/dice/", transform=tt_transform)
defect_dl = DataLoader(defect_ds, 128, shuffle=False, num_workers=3, pin_memory=True)


disc = torch.load("./discriminator.pt", map_location=torch.device('cpu'))
img = Image.open("./data/dice/0/200.jpg").convert('RGB')
img_tensor = transforms.ToTensor()(img).unsqueeze_(0)

defect_img = Image.open('data/defect/anomalous_dice/img_18010_cropped.jpg').convert('RGB')
defect_tensor = transforms.ToTensor()(defect_img).unsqueeze_(0)

In [40]:
torch.set_printoptions(precision=10, sci_mode=False)
# out = disc(img_tensor)
# print(out)
out = disc(defect_tensor)
print(out)
# print(img_tensor)
scores = []
print(defect_ds.imgs[59])
for i, image in enumerate(defect_ds):
    score = disc(image[0].unsqueeze_(0))
    scores.append(score[0][0].item())
    print(f"{i}: {score}")
mean = sum(scores) / len(scores)
scores_max = max(scores)
scores_min = min(scores)
print(f"Min: {scores_min}\nMax: {scores_max}\nMean: {mean}")

tensor([[0.0222897958]], grad_fn=<SigmoidBackward>)
('data/dice/0\\1050.jpg', 0)
0: tensor([[0.0510212928]], grad_fn=<SigmoidBackward>)
1: tensor([[0.0457171053]], grad_fn=<SigmoidBackward>)
2: tensor([[0.0130625442]], grad_fn=<SigmoidBackward>)
3: tensor([[0.0136622321]], grad_fn=<SigmoidBackward>)
4: tensor([[0.9377490878]], grad_fn=<SigmoidBackward>)
5: tensor([[0.6608687639]], grad_fn=<SigmoidBackward>)
6: tensor([[0.8343625665]], grad_fn=<SigmoidBackward>)
7: tensor([[0.9261678457]], grad_fn=<SigmoidBackward>)
8: tensor([[0.9809196591]], grad_fn=<SigmoidBackward>)
9: tensor([[0.9754683375]], grad_fn=<SigmoidBackward>)
10: tensor([[0.9710694551]], grad_fn=<SigmoidBackward>)
11: tensor([[0.9834559560]], grad_fn=<SigmoidBackward>)
12: tensor([[0.9010555148]], grad_fn=<SigmoidBackward>)
13: tensor([[0.4544916451]], grad_fn=<SigmoidBackward>)
14: tensor([[0.0198813826]], grad_fn=<SigmoidBackward>)
15: tensor([[0.7014719248]], grad_fn=<SigmoidBackward>)
16: tensor([[0.7300505638]], grad

147: tensor([[0.2514686882]], grad_fn=<SigmoidBackward>)
148: tensor([[0.1612489969]], grad_fn=<SigmoidBackward>)
149: tensor([[0.2879832685]], grad_fn=<SigmoidBackward>)
150: tensor([[0.2374882102]], grad_fn=<SigmoidBackward>)
151: tensor([[0.1797787249]], grad_fn=<SigmoidBackward>)
152: tensor([[0.3794538081]], grad_fn=<SigmoidBackward>)
153: tensor([[0.1024447307]], grad_fn=<SigmoidBackward>)
154: tensor([[0.1787406951]], grad_fn=<SigmoidBackward>)
155: tensor([[0.0940565467]], grad_fn=<SigmoidBackward>)
156: tensor([[0.0036606113]], grad_fn=<SigmoidBackward>)
157: tensor([[0.3754075170]], grad_fn=<SigmoidBackward>)
158: tensor([[0.1154105812]], grad_fn=<SigmoidBackward>)
159: tensor([[0.0930487886]], grad_fn=<SigmoidBackward>)
160: tensor([[0.3258868456]], grad_fn=<SigmoidBackward>)
161: tensor([[0.4032709002]], grad_fn=<SigmoidBackward>)
162: tensor([[0.1183552593]], grad_fn=<SigmoidBackward>)
163: tensor([[0.1290977150]], grad_fn=<SigmoidBackward>)
164: tensor([[0.3332997561]], g

291: tensor([[0.9157488942]], grad_fn=<SigmoidBackward>)
292: tensor([[0.9634841084]], grad_fn=<SigmoidBackward>)
293: tensor([[0.9653711319]], grad_fn=<SigmoidBackward>)
294: tensor([[0.9536482692]], grad_fn=<SigmoidBackward>)
295: tensor([[0.9699457884]], grad_fn=<SigmoidBackward>)
296: tensor([[0.9264052510]], grad_fn=<SigmoidBackward>)
297: tensor([[0.9453334212]], grad_fn=<SigmoidBackward>)
298: tensor([[0.9218899012]], grad_fn=<SigmoidBackward>)
299: tensor([[0.9593005180]], grad_fn=<SigmoidBackward>)
300: tensor([[0.0211612470]], grad_fn=<SigmoidBackward>)
301: tensor([[0.0244294293]], grad_fn=<SigmoidBackward>)
302: tensor([[0.9668074250]], grad_fn=<SigmoidBackward>)
303: tensor([[0.9492033124]], grad_fn=<SigmoidBackward>)
304: tensor([[0.9671770334]], grad_fn=<SigmoidBackward>)
305: tensor([[0.9258648753]], grad_fn=<SigmoidBackward>)
306: tensor([[0.9662967920]], grad_fn=<SigmoidBackward>)
307: tensor([[0.9578903913]], grad_fn=<SigmoidBackward>)
308: tensor([[0.9450062513]], g

436: tensor([[0.9365317822]], grad_fn=<SigmoidBackward>)
437: tensor([[0.9566985965]], grad_fn=<SigmoidBackward>)
438: tensor([[0.9389473200]], grad_fn=<SigmoidBackward>)
439: tensor([[0.9585196376]], grad_fn=<SigmoidBackward>)
440: tensor([[0.9208756685]], grad_fn=<SigmoidBackward>)
441: tensor([[0.9069881439]], grad_fn=<SigmoidBackward>)
442: tensor([[0.9400402308]], grad_fn=<SigmoidBackward>)
443: tensor([[0.9408861399]], grad_fn=<SigmoidBackward>)
444: tensor([[0.9484502673]], grad_fn=<SigmoidBackward>)
445: tensor([[0.0491888411]], grad_fn=<SigmoidBackward>)
446: tensor([[0.9693295360]], grad_fn=<SigmoidBackward>)
447: tensor([[0.9245005250]], grad_fn=<SigmoidBackward>)
448: tensor([[0.9677955508]], grad_fn=<SigmoidBackward>)
449: tensor([[0.9188212156]], grad_fn=<SigmoidBackward>)
450: tensor([[0.9523645639]], grad_fn=<SigmoidBackward>)
451: tensor([[0.9552172422]], grad_fn=<SigmoidBackward>)
452: tensor([[0.9692172408]], grad_fn=<SigmoidBackward>)
453: tensor([[0.9672819972]], g

581: tensor([[0.9983667731]], grad_fn=<SigmoidBackward>)
582: tensor([[0.9975912571]], grad_fn=<SigmoidBackward>)
583: tensor([[0.9980304837]], grad_fn=<SigmoidBackward>)
584: tensor([[0.9985381365]], grad_fn=<SigmoidBackward>)
585: tensor([[0.9954460859]], grad_fn=<SigmoidBackward>)
586: tensor([[0.9994786382]], grad_fn=<SigmoidBackward>)
587: tensor([[0.9968011379]], grad_fn=<SigmoidBackward>)
588: tensor([[0.9965423942]], grad_fn=<SigmoidBackward>)
589: tensor([[0.0181931369]], grad_fn=<SigmoidBackward>)
590: tensor([[0.9983834028]], grad_fn=<SigmoidBackward>)
591: tensor([[0.9953489900]], grad_fn=<SigmoidBackward>)
592: tensor([[0.9915368557]], grad_fn=<SigmoidBackward>)
593: tensor([[0.9942181110]], grad_fn=<SigmoidBackward>)
594: tensor([[0.9978007674]], grad_fn=<SigmoidBackward>)
595: tensor([[0.9987126589]], grad_fn=<SigmoidBackward>)
596: tensor([[0.9963261485]], grad_fn=<SigmoidBackward>)
597: tensor([[0.9979870319]], grad_fn=<SigmoidBackward>)
598: tensor([[0.9983152151]], g

725: tensor([[0.9763467312]], grad_fn=<SigmoidBackward>)
726: tensor([[0.9782307148]], grad_fn=<SigmoidBackward>)
727: tensor([[0.9726759195]], grad_fn=<SigmoidBackward>)
728: tensor([[0.9608958364]], grad_fn=<SigmoidBackward>)
729: tensor([[0.9633474350]], grad_fn=<SigmoidBackward>)
730: tensor([[0.9709270597]], grad_fn=<SigmoidBackward>)
731: tensor([[0.9695060253]], grad_fn=<SigmoidBackward>)
732: tensor([[0.9008533955]], grad_fn=<SigmoidBackward>)
733: tensor([[0.0068635209]], grad_fn=<SigmoidBackward>)
734: tensor([[0.9755318165]], grad_fn=<SigmoidBackward>)
735: tensor([[0.9340893626]], grad_fn=<SigmoidBackward>)
736: tensor([[0.9797414541]], grad_fn=<SigmoidBackward>)
737: tensor([[0.9873473644]], grad_fn=<SigmoidBackward>)
738: tensor([[0.9797359705]], grad_fn=<SigmoidBackward>)
739: tensor([[0.9678613544]], grad_fn=<SigmoidBackward>)
740: tensor([[0.9775505662]], grad_fn=<SigmoidBackward>)
741: tensor([[0.9766212106]], grad_fn=<SigmoidBackward>)
742: tensor([[0.9844761491]], g

869: tensor([[0.9157994986]], grad_fn=<SigmoidBackward>)
870: tensor([[0.9369822145]], grad_fn=<SigmoidBackward>)
871: tensor([[0.9498478770]], grad_fn=<SigmoidBackward>)
872: tensor([[0.8138000965]], grad_fn=<SigmoidBackward>)
873: tensor([[0.7454774976]], grad_fn=<SigmoidBackward>)
874: tensor([[0.8700198531]], grad_fn=<SigmoidBackward>)
875: tensor([[0.9942654967]], grad_fn=<SigmoidBackward>)
876: tensor([[0.9948423505]], grad_fn=<SigmoidBackward>)
877: tensor([[0.4013767838]], grad_fn=<SigmoidBackward>)
878: tensor([[0.0171798486]], grad_fn=<SigmoidBackward>)
879: tensor([[0.7203568816]], grad_fn=<SigmoidBackward>)
880: tensor([[0.5419529676]], grad_fn=<SigmoidBackward>)
881: tensor([[0.9396076202]], grad_fn=<SigmoidBackward>)
882: tensor([[0.9856474400]], grad_fn=<SigmoidBackward>)
883: tensor([[0.9824056029]], grad_fn=<SigmoidBackward>)
884: tensor([[0.9788996577]], grad_fn=<SigmoidBackward>)
885: tensor([[0.9833910465]], grad_fn=<SigmoidBackward>)
886: tensor([[0.9776581526]], g

1014: tensor([[0.4326073527]], grad_fn=<SigmoidBackward>)
1015: tensor([[0.6782510877]], grad_fn=<SigmoidBackward>)
1016: tensor([[0.9474183917]], grad_fn=<SigmoidBackward>)
1017: tensor([[0.9872242212]], grad_fn=<SigmoidBackward>)
1018: tensor([[0.9872016907]], grad_fn=<SigmoidBackward>)
1019: tensor([[0.9820674658]], grad_fn=<SigmoidBackward>)
1020: tensor([[0.9921971560]], grad_fn=<SigmoidBackward>)
1021: tensor([[0.9434913397]], grad_fn=<SigmoidBackward>)
1022: tensor([[0.0050549763]], grad_fn=<SigmoidBackward>)
1023: tensor([[0.4256887138]], grad_fn=<SigmoidBackward>)
1024: tensor([[0.7548147440]], grad_fn=<SigmoidBackward>)
1025: tensor([[0.7207316160]], grad_fn=<SigmoidBackward>)
1026: tensor([[0.8150196671]], grad_fn=<SigmoidBackward>)
1027: tensor([[0.9448783994]], grad_fn=<SigmoidBackward>)
1028: tensor([[0.8294593096]], grad_fn=<SigmoidBackward>)
1029: tensor([[0.9213984013]], grad_fn=<SigmoidBackward>)
1030: tensor([[0.8708149195]], grad_fn=<SigmoidBackward>)
1031: tensor([

In [9]:
good_mean = 0.73189
defect_mean = 0.04
threshold = 0.7

In [14]:
img_folder = "data/test/"
for root, folders, files in os.walk(img_folder):
    for file in files:
        fp = path.join(root, file)
        print(fp)
        img = Image.open(fp).convert('RGB')
        img_tensor = transforms.ToTensor()(img).unsqueeze_(0)
        print(disc(img_tensor))

data/test/ab_1.jpg
tensor([[0.0021875894]], grad_fn=<SigmoidBackward>)
data/test/ab_2.jpg
tensor([[0.0011679222]], grad_fn=<SigmoidBackward>)
data/test/ab_3.jpg
tensor([[0.0005938788]], grad_fn=<SigmoidBackward>)
data/test/ab_4.jpg
tensor([[0.0008174704]], grad_fn=<SigmoidBackward>)
data/test/ab_5.jpg
tensor([[0.0002195729]], grad_fn=<SigmoidBackward>)
data/test/ab_6.jpg
tensor([[0.0002187502]], grad_fn=<SigmoidBackward>)
data/test/ab_7.jpg
tensor([[0.0014937610]], grad_fn=<SigmoidBackward>)
data/test/ab_8.jpg
tensor([[0.0009116972]], grad_fn=<SigmoidBackward>)
data/test/ab_9.jpg
tensor([[0.0002127873]], grad_fn=<SigmoidBackward>)


In [72]:
import random

for root, folders, files in os.walk("data/dice/0/"):
    pictures = [path.join(root, file) for file in files]

choices = random.choices(pictures, k=50)

for root, folders, files in os.walk("data/defect/anomalous_dice/"):
    pictures = [path.join(root, file) for file in files]
    
choices.extend(random.choices(pictures, k=15))

random.shuffle(choices)

choices

['data/dice/0/841.jpg',
 'data/dice/0/56.jpg',
 'data/dice/0/844.jpg',
 'data/defect/anomalous_dice/img_17953_cropped.jpg',
 'data/dice/0/917.jpg',
 'data/dice/0/471.jpg',
 'data/defect/anomalous_dice/img_17482_cropped.jpg',
 'data/dice/0/898.jpg',
 'data/dice/0/608.jpg',
 'data/dice/0/50.jpg',
 'data/defect/anomalous_dice/img_17671_cropped.jpg',
 'data/dice/0/524.jpg',
 'data/dice/0/1038.jpg',
 'data/dice/0/27.jpg',
 'data/dice/0/613.jpg',
 'data/dice/0/247.jpg',
 'data/dice/0/844.jpg',
 'data/defect/anomalous_dice/img_17625_cropped.jpg',
 'data/dice/0/600.jpg',
 'data/dice/0/335.jpg',
 'data/defect/anomalous_dice/img_17516_cropped.jpg',
 'data/dice/0/1070.jpg',
 'data/dice/0/142.jpg',
 'data/dice/0/143.jpg',
 'data/dice/0/594.jpg',
 'data/dice/0/667.jpg',
 'data/dice/0/307.jpg',
 'data/dice/0/781.jpg',
 'data/dice/0/136.jpg',
 'data/dice/0/589.jpg',
 'data/dice/0/785.jpg',
 'data/dice/0/356.jpg',
 'data/dice/0/514.jpg',
 'data/dice/0/190.jpg',
 'data/dice/0/819.jpg',
 'data/dice/0/63

In [74]:
out = []
stats = (0.5, 0.5, 0.5), (0.5, 0.5, 0.5)
tt_transform = tt.Compose([tt.Resize(128),
                             tt.CenterCrop(128),
                             tt.ToTensor(),
                             tt.Normalize(*stats)])
threshold = 0.7
disc = torch.load("./discriminator.pt", map_location=torch.device('cpu'))
for img_path in choices:
    img = Image.open(img_path).convert('RGB')
    img_tensor = tt_transform(img).unsqueeze_(0)
    score = disc(img_tensor)[0].item()
    score = round(score, 2)
    predict = 1 if score >= threshold else 0
    if "anomalous_dice" in img_path:
        out.append([img_path, score, 0, predict])
    else:
        out.append([img_path, score, 1, predict])

df = pd.DataFrame(out, columns=["path", "score", "real_class", "predicted_class"])

In [75]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None): 
    display(df)

path  score  real_class  \
0                                data/dice/0/841.jpg   0.88           1   
1                                 data/dice/0/56.jpg   0.02           1   
2                                data/dice/0/844.jpg   0.93           1   
3   data/defect/anomalous_dice/img_17953_cropped.jpg   0.00           0   
4                                data/dice/0/917.jpg   0.74           1   
5                                data/dice/0/471.jpg   0.97           1   
6   data/defect/anomalous_dice/img_17482_cropped.jpg   0.00           0   
7                                data/dice/0/898.jpg   0.56           1   
8                                data/dice/0/608.jpg   0.99           1   
9                                 data/dice/0/50.jpg   0.02           1   
10  data/defect/anomalous_dice/img_17671_cropped.jpg   0.00           0   
11                               data/dice/0/524.jpg   1.00           1   
12                              data/dice/0/1038.jpg   0.98           1   
13                                data/dice/0/27.jpg   0.02           1   
14                               data/dice/0/613.jpg   1.00           1   
15                               data/dice/0/247.jpg   0.11           1   
16                               data/dice/0/844.jpg   0.93           1   
17  data/defect/anomalous_dice/img_17625_cropped.jpg   0.00           0   
18                               data/dice/0/600.jpg   1.00           1   
19                               data/dice/0/335.jpg   0.96           1   
20  data/defect/anomalous_dice/img_17516_cropped.jpg   0.04           0   
21                              data/dice/0/1070.jpg   0.98           1   
22                               data/dice/0/142.jpg   0.19           1   
23                               data/dice/0/143.jpg   0.39           1   
24                               data/dice/0/594.jpg   0.99           1   
25                               data/dice/0/667.jpg   1.00           1   
26                               data/dice/0/307.jpg   0.93           1   
27                               data/dice/0/781.jpg   0.98           1   
28                               data/dice/0/136.jpg   0.09           1   
29                               data/dice/0/589.jpg   1.00           1   
30                               data/dice/0/785.jpg   0.96           1   
31                               data/dice/0/356.jpg   0.95           1   
32                               data/dice/0/514.jpg   1.00           1   
33                               data/dice/0/190.jpg   0.25           1   
34                               data/dice/0/819.jpg   0.40           1   
35                               data/dice/0/636.jpg   1.00           1   
36                               data/dice/0/331.jpg   0.97           1   
37                               data/dice/0/967.jpg   0.46           1   
38  data/defect/anomalous_dice/img_17482_cropped.jpg   0.00           0   
39                               data/dice/0/130.jpg   0.18           1   
40                               data/dice/0/994.jpg   0.86           1   
41                              data/dice/0/1029.jpg   0.98           1   
42  data/defect/anomalous_dice/img_18068_cropped.jpg   0.00           0   
43                                data/dice/0/39.jpg   0.01           1   
44  data/defect/anomalous_dice/img_18165_cropped.jpg   0.00           0   
45  data/defect/anomalous_dice/img_17516_cropped.jpg   0.04           0   
46                               data/dice/0/177.jpg   0.33           1   
47                               data/dice/0/983.jpg   0.98           1   
48                              data/dice/0/1020.jpg   0.93           1   
49                               data/dice/0/146.jpg   0.38           1   
50  data/defect/anomalous_dice/img_17852_cropped.jpg   0.00           0   
51                               data/dice/0/314.jpg   0.89           1   
52  data/defect/anomalous_dice/img_17517_cropped.jpg   0.11           0  